### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by mvoodarla** [bshall/urhythmic#3]
Currently getting this issue when running `python train_vocoder.py mok/dataset/ mok/`. Also tried changing the `num_workers` in the script from 8 to 1 on the loaders. Any ideas how to resolve?

```
2023-08-03 17:52:56.558490: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-03 17:52:57.569726: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:__main__:PyTorch version: 2.0.1+cu117
INFO:__main__:CUDA version: 11.7
INFO:__main__:CUDNN version: 8600
INFO:__main__:CUDNN enabled: True
INFO:__main__:CUDNN deterministic: False
INFO:__main__:CUDNN benchmark: False
INFO:__main__:# of GPUS: 1
2023-08-03 17:53:01.825974: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-03 17:53:02.799741: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO:__mp_main__:********************************************************************************
INFO:__mp_main__:batch size: 8
INFO:__mp_main__:iterations per epoch: 7
INFO:__mp_main__:total number of epochs: 428572
INFO:__mp_main__:started at epoch: 1
INFO:__mp_main__:********************************************************************************

2023-08-03 17:53:10.493759: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-03 17:53:11.466444: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
  File "/home/ubuntu/experiments/urhythmic/train_vocoder.py", line 358, in <module>
    mp.spawn(
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ubuntu/experiments/urhythmic/train_vocoder.py", line 184, in train_model
    for i, (wavs, units, tgts) in enumerate(train_loader, 1):
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/ubuntu/miniconda3/envs/mok310/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable
```

**Comment by mvoodarla** [comment]
**Some other experiments**

Changing nothing but the `BATCH_SIZE` variable to 1 results in a different error.
```
RuntimeError: Given groups=1, weight of size [512, 256, 5], expected input[1, 270, 12] to have 256 channels, but got 270 channels instead
```

Changing both instances of `num_workers` from 8 to 1 results in the same error
```
RuntimeError: Trying to resize storage that is not resizable
```

Changing the `BATCH_SIZE` variable to 2 results in a different error.
```
RuntimeError: stack expects each tensor to be equal size, but got [270, 12] at entry 0 and [256, 26] at entry 1
```

**Comment by bshall** [comment]
Hi @mvoodarla, I think one of your utterances is really short so it's hitting the branch [here](https://github.com/bshall/urhythmic/blob/main/urhythmic/dataset.py#L107C36-L107C36), which has a bug in it (padding the wrong axis). I'll put in a fix now.

**Comment by mvoodarla** [comment]
Gotcha. To create my training set, I transcribed a 10 minute audio with Whisper and turned each generated "segment" into its own wav file. The training works if instead of doing this, I naively chop the 10 minute audio into 5 second segments.

**Comment by bshall** [comment]
I've added a fix for the issue. Let me know if it solves the problem.

Yeah, it probably best to try to get segments longer than the `SEGMENT_LENGTH` hyperparameter since otherwise you're training the model to predict padding pretty often. Not sure if it'd have any real impact but just to be safe I'd make them a little longer.

**Comment by mvoodarla** [comment]
got it. that works, thank you!
